SEED_RECALLS = [
    {
        "source_recall_id": "DEMO-001",
        "classification": "Class I",
        "product_description": "Fresh Valley Organic Baby Spinach 5 oz clamshell",
        "brand_name": "Fresh Valley",
        "recalling_firm": "Fresh Valley Foods Inc.",
        "reason_for_recall": "Potential Listeria monocytogenes contamination.",
        "distribution_pattern": "Nationwide distribution including New York, Pennsylvania, Ohio, and Michigan.",
        "recall_initiation_date": "2026-07-01",
    },
    {
        "source_recall_id": "DEMO-002",
        "classification": "Class I",
        "product_description": "Golden Grain Honey Oat Granola 12 oz pouches",
        "brand_name": "Golden Grain",
        "recalling_firm": "Golden Grain Market Co.",
        "reason_for_recall": "Undeclared peanuts on product label.",
        "distribution_pattern": "Distributed to retail stores in the United States.",
        "recall_initiation_date": "2026-06-21",
    },
    {
        "source_recall_id": "DEMO-003",
        "classification": "Class II",
        "product_description": "Harbor Catch Frozen Salmon Burgers 2 lb box",
        "brand_name": "Harbor Catch",
        "recalling_firm": "Harbor Catch Seafood LLC",
        "reason_for_recall": "Product may contain undeclared soy.",
        "distribution_pattern": "Distributed in Connecticut, Massachusetts, New Jersey, and New York.",
        "recall_initiation_date": "2026-06-10",
    },
    {
        "source_recall_id": "DEMO-004",
        "classification": "Class II",
        "product_description": "Bright Dairy Vanilla Yogurt Cups 6 pack",
        "brand_name": "Bright Dairy",
        "recalling_firm": "Bright Dairy Cooperative",
        "reason_for_recall": "Possible foreign material contamination.",
        "distribution_pattern": "Regional distribution in the Midwest.",
        "recall_initiation_date": "2026-05-28",
    },
    {
        "source_recall_id": "DEMO-005",
        "classification": "Class I",
        "product_description": "Casa Verde Mild Salsa 16 oz jars",
        "brand_name": "Casa Verde",
        "recalling_firm": "Casa Verde Foods",
        "reason_for_recall": "Potential glass fragments in jars.",
        "distribution_pattern": "Nationwide.",
        "recall_initiation_date": "2026-05-14",
    },
    {
        "source_recall_id": "DEMO-006",
        "classification": "Class II",
        "product_description": "Northline Foods Chicken Salad Sandwiches",
        "brand_name": "Northline Foods",
        "recalling_firm": "Northline Prepared Foods",
        "reason_for_recall": "Temperature abuse during transportation.",
        "distribution_pattern": "Distributed to food service locations in New York and New Jersey.",
        "recall_initiation_date": "2026-04-30",
    },
    {
        "source_recall_id": "DEMO-007",
        "classification": "Class III",
        "product_description": "Summit Trail Almond Protein Bars",
        "brand_name": "Summit Trail",
        "recalling_firm": "Summit Trail Snacks",
        "reason_for_recall": "Incorrect net weight statement.",
        "distribution_pattern": "Western United States.",
        "recall_initiation_date": "2026-04-18",
    },
    {
        "source_recall_id": "DEMO-008",
        "classification": "Class I",
        "product_description": "Blue Kettle Creamy Peanut Butter 18 oz",
        "brand_name": "Blue Kettle",
        "recalling_firm": "Blue Kettle Pantry",
        "reason_for_recall": "Potential Salmonella contamination.",
        "distribution_pattern": "Online and retail distribution nationwide.",
        "recall_initiation_date": "2026-03-26",
    },
    {
        "source_recall_id": "DEMO-009",
        "classification": "Class II",
        "product_description": "Metro Market Chocolate Chip Muffins",
        "brand_name": "Metro Market",
        "recalling_firm": "Metro Market Bakery",
        "reason_for_recall": "Undeclared milk allergen.",
        "distribution_pattern": "Distributed in Ontario and northeastern United States.",
        "recall_initiation_date": "2026-03-05",
    },
    {
        "source_recall_id": "DEMO-010",
        "classification": "Class I",
        "product_description": "Evergreen Sprouts Alfalfa Sprouts 4 oz",
        "brand_name": "Evergreen Sprouts",
        "recalling_firm": "Evergreen Sprouts Farm",
        "reason_for_recall": "Potential E. coli contamination.",
        "distribution_pattern": "Distributed in New York, Vermont, and Pennsylvania.",
        "recall_initiation_date": "2026-02-13",
    },
]

BASE_INVENTORY = [
    ("Fresh Valley Organic Spinach", "Fresh Valley", "123456789012", "L2408", 48, "Hospital Cafeteria - Cold Storage", "hospital", "critical", True, "Northeast", "Northline Foods"),
    ("FreshValley baby spinach clamshell", "Fresh Valley", "", "L2409", 26, "Campus Dining - Main Kitchen", "campus_dining", "high", True, "Northeast", "Northline Foods"),
    ("Golden Grain Honey Oat Granola", "Golden Grain", "887766554433", "GG0612", 80, "Downtown Grocery - Aisle 3", "grocery_floor", "high", True, "Northeast", "Grocery Direct"),
    ("Harbor Catch salmon burger frozen", "Harbor Catch", "444555666777", "HC290", 18, "Food Bank - Distribution Dock", "food_bank", "critical", True, "Northeast", "SeaBoard Supply"),
    ("Casa Verde Mild Salsa", "Casa Verde", "222333444555", "CV77", 64, "Downtown Grocery - Aisle 5", "grocery_floor", "high", True, "Northeast", "Pantry Wholesale"),
    ("Northline chicken salad sandwich", "Northline", "333222111000", "NL041", 32, "Campus Dining - Grab and Go", "campus_dining", "high", True, "Northeast", "Northline Foods"),
    ("Blue Kettle peanut butter creamy", "Blue Kettle", "989898989898", "BK18", 54, "Food Bank - Distribution Dock", "food_bank", "critical", True, "Northeast", "Pantry Wholesale"),
    ("Evergreen alfalfa sprouts", "Evergreen Sprouts", "111999333222", "ES4", 15, "Downtown Grocery - Produce Case", "grocery_floor", "high", True, "Northeast", "Farmline"),
    ("Metro chocolate chip muffins", "Metro Market", "747474747474", "MM13", 22, "Hospital Cafeteria - Bakery", "hospital", "critical", True, "Northeast", "Metro Market Bakery"),
    ("Bright Dairy vanilla yogurt six pack", "Bright Dairy", "555666777888", "BD620", 120, "Warehouse - Cold Storage", "storage", "storage", False, "Midwest", "DairyLink"),
]

FILLER_PRODUCTS = [
    "Red Barn Tomato Soup", "Prairie Rice Blend", "Orchard Apple Juice", "Stone Mill Crackers",
    "Clearwater Tuna Cans", "Misty Morning Eggs", "Green Fork Lentils", "Silver Spoon Flour",
    "Sunrise Orange Juice", "Oak Table Pasta", "Lakeview Black Beans", "Maple Hill Syrup",
    "Urban Roast Coffee", "Harvest Moon Oats", "Cobalt Tea Bags", "Ridge Line Pickles",
    "Canyon Trail Raisins", "Market House Tortillas", "Polar Cream Ice Cream", "Field Day Corn",
    "Cedar Grove Hummus", "Atlantic Pasta Sauce", "Bright Leaf Lettuce", "Hilltop Cheddar",
    "Village Bakery Sourdough", "North Star Sparkling Water", "Amber Jar Mustard", "Riverbend Quinoa",
    "Elm Street Pretzels", "Bayside Coconut Milk", "Valley View Carrots", "Crestline Black Tea",
]


def _items(names, location, location_type, criticality, public_serving, region, supplier, quantity_base=18):
    rows = []
    for index, name in enumerate(names):
        tokens = name.split()
        brand = " ".join(tokens[:2]) if len(tokens) > 1 else tokens[0]
        rows.append(
            (
                name,
                brand,
                f"9{index + 1:011d}",
                f"{tokens[0][:2].upper()}{index + 101}",
                quantity_base + ((index * 7) % 86),
                location(index),
                location_type,
                criticality,
                public_serving,
                region,
                supplier(index),
            )
        )
    return rows


DEMO_COMPANY_PROFILES = [
    {
        "id": "metro_mart_grocery",
        "name": "MetroMart Grocery",
        "company_type": "Grocery store",
        "description": "Neighborhood grocery with produce, dairy, packaged foods, bakery, frozen foods, and shelf-stable pantry aisles.",
        "risk_context": "Public-facing retail shelves create high urgency when Class I recalls affect ready-to-eat or widely stocked products.",
        "recommended": True,
        "items": _items(
            [
                "Fresh Valley Organic Spinach", "Golden Grain Honey Oat Granola", "Casa Verde Mild Salsa",
                "Evergreen Alfalfa Sprouts", "Bright Dairy Vanilla Yogurt", "Blue Kettle Creamy Peanut Butter",
                "Metro Market Chocolate Chip Muffins", "Harbor Catch Frozen Salmon Burgers", "Red Barn Tomato Soup",
                "Orchard Apple Juice", "Stone Mill Crackers", "Clearwater Tuna Cans", "Sunrise Orange Juice",
                "Oak Table Pasta", "Lakeview Black Beans", "Maple Hill Syrup", "Urban Roast Coffee",
                "Market House Tortillas", "Polar Cream Ice Cream", "Bright Leaf Lettuce", "Village Bakery Sourdough",
                "Hilltop Cheddar", "Amber Jar Mustard", "Valley View Carrots",
            ],
            lambda i: ["MetroMart Grocery - Produce", "MetroMart Grocery - Dairy", "MetroMart Grocery - Pantry", "MetroMart Grocery - Frozen", "MetroMart Grocery - Bakery"][i % 5],
            "grocery_floor",
            "high",
            True,
            "Northeast",
            lambda i: ["Grocery Direct", "Farmline", "DairyLink", "Pantry Wholesale"][i % 4],
            24,
        ),
    },
    {
        "id": "oak_ember_steakhouse",
        "name": "Oak & Ember Steakhouse",
        "company_type": "Restaurant",
        "description": "Full-service steakhouse with proteins, seafood, sauces, dairy, produce, desserts, and prep kitchen inventory.",
        "risk_context": "Prepared meals and same-day service mean exposure decisions need fast kitchen-level review.",
        "recommended": False,
        "items": _items(
            [
                "Prime Ridge Beef Ribeye", "Prime Ridge Beef Filet", "Harbor Catch Frozen Salmon Burgers",
                "Harbor Catch Shrimp Skewers", "Casa Verde Mild Salsa", "Bright Dairy Heavy Cream",
                "Bright Dairy Vanilla Yogurt", "Blue Kettle Peanut Butter Sauce", "Fresh Valley Baby Spinach",
                "Evergreen Alfalfa Sprouts", "Metro Market Chocolate Chip Muffins", "Stone Mill Dinner Rolls",
                "Red Barn Steak Sauce", "Golden Grain Bread Crumbs", "Oak Table Pasta", "Field Day Sweet Corn",
                "Hilltop Cheddar", "Amber Jar Dijon Mustard", "Valley View Carrots", "Village Bakery Cheesecake",
                "Clearwater Tuna Portions", "Prairie Rice Blend", "Bright Leaf Lettuce", "Cedar Grove Hummus",
            ],
            lambda i: ["Oak & Ember - Walk-In Cooler", "Oak & Ember - Prep Line", "Oak & Ember - Dry Storage", "Oak & Ember - Freezer"][i % 4],
            "restaurant_kitchen",
            "high",
            True,
            "Northeast",
            lambda i: ["Chef Supply Co", "SeaBoard Supply", "DairyLink", "Farmline"][i % 4],
            10,
        ),
    },
    {
        "id": "campus_table_dining",
        "name": "Campus Table Dining",
        "company_type": "University dining",
        "description": "Campus dining group with bulk ingredients, cafeteria stock, grab-and-go sandwiches, beverages, and bakery items.",
        "risk_context": "Large batch preparation and student-facing service increase review urgency for allergen and pathogen recalls.",
        "recommended": False,
        "items": _items(
            [
                "Northline Foods Chicken Salad Sandwiches", "FreshValley Baby Spinach Clamshell", "Golden Grain Honey Oat Granola",
                "Bright Dairy Vanilla Yogurt Cups", "Metro Market Chocolate Chip Muffins", "Casa Verde Mild Salsa",
                "Blue Kettle Creamy Peanut Butter", "Prairie Rice Blend", "Market House Tortillas", "Sunrise Orange Juice",
                "Cobalt Tea Bags", "Urban Roast Coffee", "Lakeview Black Beans", "Field Day Corn", "Hilltop Cheddar",
                "Village Bakery Sourdough", "Bright Leaf Lettuce", "Valley View Carrots", "Cedar Grove Hummus",
                "Orchard Apple Juice", "Stone Mill Crackers", "Harvest Moon Oats", "Misty Morning Eggs", "Red Barn Tomato Soup",
            ],
            lambda i: ["Campus Table - Main Kitchen", "Campus Table - Grab and Go", "Campus Table - Dining Hall", "Campus Table - Cold Storage"][i % 4],
            "campus_dining",
            "high",
            True,
            "Northeast",
            lambda i: ["Northline Foods", "Campus Supply Network", "DairyLink", "Grocery Direct"][i % 4],
            35,
        ),
    },
    {
        "id": "northside_hospital_cafeteria",
        "name": "Northside Hospital Cafeteria",
        "company_type": "Hospital food service",
        "description": "Hospital cafeteria and patient meal stock with cold storage, bakery, pantry, and high-criticality service lines.",
        "risk_context": "Vulnerable populations and patient meal service make exposure scoring stricter than ordinary retail.",
        "recommended": False,
        "items": _items(
            [
                "Fresh Valley Organic Spinach", "Bright Dairy Vanilla Yogurt Cups", "Metro Market Chocolate Chip Muffins",
                "Northline Foods Chicken Salad Sandwiches", "Evergreen Alfalfa Sprouts", "Golden Grain Honey Oat Granola",
                "Blue Kettle Creamy Peanut Butter", "Orchard Apple Juice", "Prairie Rice Blend", "Lakeview Black Beans",
                "Red Barn Tomato Soup", "Stone Mill Crackers", "Sunrise Orange Juice", "Harvest Moon Oats",
                "Misty Morning Eggs", "Hilltop Cheddar", "Bright Leaf Lettuce", "Valley View Carrots",
                "Village Bakery Sourdough", "Crestline Black Tea", "Urban Roast Coffee", "Clearwater Tuna Cans",
                "Field Day Corn", "Cedar Grove Hummus",
            ],
            lambda i: ["Northside Hospital - Patient Meals", "Northside Hospital - Cafeteria", "Northside Hospital - Cold Storage", "Northside Hospital - Pantry"][i % 4],
            "hospital",
            "critical",
            True,
            "Northeast",
            lambda i: ["MedFood Distribution", "DairyLink", "Northline Foods", "Farmline"][i % 4],
            28,
        ),
    },
    {
        "id": "harvest_hope_food_bank",
        "name": "Harvest Hope Food Bank",
        "company_type": "Food bank",
        "description": "Food bank with donated shelf-stable goods, dairy, produce, frozen proteins, and distribution dock inventory.",
        "risk_context": "Distributed products can leave the facility quickly, so affected lots need traceable triage.",
        "recommended": False,
        "items": _items(
            [
                "Blue Kettle Creamy Peanut Butter", "Casa Verde Mild Salsa", "Golden Grain Honey Oat Granola",
                "Harbor Catch Frozen Salmon Burgers", "Evergreen Alfalfa Sprouts", "Red Barn Tomato Soup",
                "Prairie Rice Blend", "Clearwater Tuna Cans", "Green Fork Lentils", "Silver Spoon Flour",
                "Lakeview Black Beans", "Maple Hill Syrup", "Market House Tortillas", "Field Day Corn",
                "Bayside Coconut Milk", "Valley View Carrots", "Bright Dairy Vanilla Yogurt", "Hilltop Cheddar",
                "Orchard Apple Juice", "Stone Mill Crackers", "Village Bakery Sourdough", "Ridge Line Pickles",
                "Canyon Trail Raisins", "North Star Sparkling Water",
            ],
            lambda i: ["Harvest Hope - Distribution Dock", "Harvest Hope - Dry Storage", "Harvest Hope - Cold Storage", "Harvest Hope - Donation Intake"][i % 4],
            "food_bank",
            "critical",
            True,
            "Northeast",
            lambda i: ["Pantry Wholesale", "Community Donation", "Farmline", "SeaBoard Supply"][i % 4],
            45,
        ),
    },
    {
        "id": "quickbasket_convenience",
        "name": "QuickBasket Convenience",
        "company_type": "Convenience store",
        "description": "Convenience retailer with packaged meals, sandwiches, snacks, drinks, dairy, and limited grocery stock.",
        "risk_context": "Small stores need simple recall triage because products are fast-moving and staff time is limited.",
        "recommended": False,
        "items": _items(
            [
                "Northline Foods Chicken Salad Sandwiches", "Metro Market Chocolate Chip Muffins", "Golden Grain Honey Oat Granola",
                "Blue Kettle Creamy Peanut Butter", "Bright Dairy Vanilla Yogurt Cups", "Sunrise Orange Juice",
                "Orchard Apple Juice", "Stone Mill Crackers", "Elm Street Pretzels", "Canyon Trail Raisins",
                "North Star Sparkling Water", "Urban Roast Coffee", "Cobalt Tea Bags", "Market House Tortillas",
                "Casa Verde Mild Salsa", "Polar Cream Ice Cream", "Red Barn Tomato Soup", "Harvest Moon Oats",
                "Village Bakery Sourdough", "Amber Jar Mustard", "Clearwater Tuna Cans", "Maple Hill Syrup",
                "Hilltop Cheddar", "Misty Morning Eggs",
            ],
            lambda i: ["QuickBasket - Grab and Go", "QuickBasket - Snack Aisle", "QuickBasket - Beverage Cooler", "QuickBasket - Frozen Case"][i % 4],
            "convenience_store",
            "medium",
            True,
            "Northeast",
            lambda i: ["QuickServe Distribution", "DairyLink", "Pantry Wholesale", "Metro Market Bakery"][i % 4],
            12,
        ),
    },
    {
        "id": "brightpath_childcare_kitchen",
        "name": "BrightPath Childcare Kitchen",
        "company_type": "Childcare meal program",
        "description": "Childcare kitchen with breakfast, snacks, allergen-sensitive ingredients, dairy, produce, and shelf-stable meals.",
        "risk_context": "Children and allergen sensitivity make even small quantities operationally important.",
        "recommended": False,
        "items": _items(
            [
                "Bright Dairy Vanilla Yogurt Cups", "Golden Grain Honey Oat Granola", "Blue Kettle Creamy Peanut Butter",
                "Fresh Valley Organic Spinach", "Orchard Apple Juice", "Harvest Moon Oats", "Misty Morning Eggs",
                "Hilltop Cheddar", "Village Bakery Sourdough", "Valley View Carrots", "Prairie Rice Blend",
                "Lakeview Black Beans", "Field Day Corn", "Stone Mill Crackers", "Market House Tortillas",
                "Sunrise Orange Juice", "Red Barn Tomato Soup", "Bright Leaf Lettuce", "Maple Hill Syrup",
                "Canyon Trail Raisins", "Cobalt Tea Bags", "Urban Roast Coffee", "Polar Cream Ice Cream",
                "Cedar Grove Hummus",
            ],
            lambda i: ["BrightPath - Child Meal Prep", "BrightPath - Snack Pantry", "BrightPath - Cold Storage", "BrightPath - Classroom Cart"][i % 4],
            "childcare_kitchen",
            "critical",
            True,
            "Northeast",
            lambda i: ["Child Nutrition Supply", "DairyLink", "Grocery Direct", "Farmline"][i % 4],
            8,
        ),
    },
    {
        "id": "summit_events_catering",
        "name": "Summit Events Catering",
        "company_type": "Catering company",
        "description": "Event caterer with prepared foods, sauces, proteins, bakery goods, transport coolers, and staging inventory.",
        "risk_context": "Off-site event service makes location and lot traceability important after food leaves the kitchen.",
        "recommended": False,
        "items": _items(
            [
                "Northline Foods Chicken Salad Sandwiches", "Harbor Catch Frozen Salmon Burgers", "Casa Verde Mild Salsa",
                "Fresh Valley Organic Spinach", "Evergreen Alfalfa Sprouts", "Metro Market Chocolate Chip Muffins",
                "Bright Dairy Heavy Cream", "Bright Dairy Vanilla Yogurt", "Golden Grain Bread Crumbs",
                "Stone Mill Dinner Rolls", "Village Bakery Sourdough", "Blue Kettle Peanut Butter Sauce",
                "Prairie Rice Blend", "Market House Tortillas", "Hilltop Cheddar", "Bright Leaf Lettuce",
                "Valley View Carrots", "Clearwater Tuna Portions", "Field Day Corn", "Red Barn Tomato Sauce",
                "Urban Roast Coffee", "Cobalt Tea Bags", "Orchard Apple Juice", "Cedar Grove Hummus",
            ],
            lambda i: ["Summit Events - Prep Kitchen", "Summit Events - Transport Cooler", "Summit Events - Dry Storage", "Summit Events - Event Staging"][i % 4],
            "catering",
            "high",
            True,
            "Northeast",
            lambda i: ["Chef Supply Co", "SeaBoard Supply", "DairyLink", "Event Pantry Network"][i % 4],
            18,
        ),
    },
]
